---
title: "KI-Nutzung"
---

## Generelle Erlaubnis

In diesem Modul ist die Nutzung von künstlicher Intelligenz (KI) zur Bearbeitung von (Prüfungs-)aufgaben ausdrücklich **erlaubt**. Wir sind realistisch und sehen, dass KI aus dem Studien- und Arbeitsalltag nicht mehr wegzudenken ist. Daher möchten wir euch dabei unterstützen, KI und KI-basierte Ergebnisse besser nutzen, verstehen, und beurteilen zu können.

## KI in der Lehre im Modul

Wir selbst setzen für unserer Lehre in diesem Modul auf KI. Im Rahmen eines durch die "Lehrförderung für die Akademische Zukunftsfähigkeit" bewilligten Projektes erstellen wir Übungsaufgaben zur eigenständigen Bearbeitung, zu denen ihr ein unmittelbares und individuelles KI-generiertes Feedback erhaltet. Dazu greifen wir auf ein lokales KI-System zurück, welches ihr auf euren Laptop installiert. Wie das alles geht, lernt ihr im Rahmen des Moduls.

Zudem hilft uns KI in Teilen bei der Erstellung von Lehrinhalten und Übungsaufgaben. So kann es etwa sein, dass der zugrundeliegende Programmiercode für manche Übungsaufgaben, oder einzelne Folien die wir präsentieren mit Hilfe von KI-System erstellt wurden. Bei der Bewertungen von Prüfungsleistungen nutzen wir keine KI!

## Datenschutz, IT-Sicherheit, KI-Richtlinien

Für die Bearbeitung der Übungsaufgaben benötigt ihr ein lokales KI-System (Ollama). Diese Open-Source Software ist kostenlos und kann ohne Anmeldung installiert und genutzt werden. Da es sich um ein lokales KI-System handelt, verbleiben alle eure Daten und Eingaben auf eurem Gerät und werden nicht geteilt. Darüber hinaus könnt ihr bei Bedarf selbstverständlich auch Online-Tools kommerzieller Anbieter nutzen. Dies wird jedoch weder von uns erwartet noch ist es für das Modul erforderlich. Bitte beachtet bei allen Tätigkeiten die Einhaltung der aktuell gültigen KI-Richtlinien unserer Universität.

## KI in Prüfungsleistungen

Ihr dürft ausdrücklich KI im Rahmen der Prüfungsleistungen des Moduls benutzen, sofern ihr transparent macht welche Tools ihr für welche Zwecke genutzt habt. Beachtet jedoch, dass wir gezielt Prüfungsformate verwenden, bei denen wir davon ausgehen, dass die zentrale Leistung nicht von einer KI übernommen werden kann. Bei der Präsentation bedeutet dass, das wir in der Bewertung einen besonderen Fokus auf die Diskussion legen. Ihr sollten alle vorgestellten Inhalte soweit verstanden haben, dass ihr in der Lage seid sie kritisch vor der Gruppe zu verteidigen und zu diskutieren. Bei der Abgabe der Visualisierung handelt es sich in erster Linie um eine kreative Aufgabe, die nur bedingt von einer KI erfüllt werden kann. Zudem legen wir hier großen Wert auf die Reproduzierbarkeit der Abgabe. Das heißt, wir erwarten, dass wir mit Hilfe des abgegebenen Codes die Visualisierung erfolgreich auf unseren eigenen Geräten nachbauen können. Auch dies erfordert bei der Erstellung der Abgabe die Anwendung eigener erlernter Kompetenzen über die Nutzung von KI hinaus.