---
title: "Prüfungen"
---
## Modulprüfungen
Im Rahmen des Moduls sind zwei benotete Prüfungen zu absolvieren:

1. Eine Projektpräsentation (5 min Vortrag + 10 min Diskussion) in der die Methodik und Ergebnisse einer selbstständig durchgeführten Datenanalyse in 2er-Teams präsentiert werden.
2. Abgabe einer Dokumentation (in Form einer Visualisierung inklusive Code zur Reproduktion).

### Projektpräsentation

#### Anforderungen

- Analyse eines sportbezogenen Datensatzes (aus einer vorgegebenen Auswahl an Datensätzen).
- Die Analyse muss eine Form von Modellierung/statistische Auswertung beeinhalten (über rein deskriptive Statistik hinaus).
- Die Analyseidee, -methodik, und -ergebnisse werden in der letzten Semesterwoche im Rahmen des Seminars präsentiert (5 min Kurzpräsentation + 10 min Diskussion).
- das Präsentationsformat ist offen (z.B. revealjs, pptx, pdf).
- die Projekte werden in 2er-Gruppen durchgeführt, wer den Vortrag präsentiert wird unmittelbar vorher ausgewürfelt, die Diskussion wird von beiden Studierenden geführt. Es gibt eine gemeinsame Note.

#### Bewertungskriterien

- Inhalt
- Präsentation 
- Form 
- Diskussion
- Gesamteindruck

### Dokumentation (in Form einer Visualisierung)

#### Anforderungen

- ein sportbezogener Datensatz (anderer als in Projektpräsentation) wird verarbeitet und visualisiert. Die Wahl des Datensatzes ist dabei freigestellt (z.B., Download eines vorhandenen Datensatzes, Webscraping einer Website, eigene Datenerhebung).
- Erstellung einer interaktiven Visualisierung (z.B. in Form eines Dashboard).
- Abgabe als reproduzierbares Packages (in Form eines zip-files mit Daten und kommentiertem Code). Der Code soll ohne Fehler auf den Geräten der Dozierenden laufen können und die exakte Visualisierung erstellen.

#### Bewertungskriterien

- Reproduzierbarkeit
- Datenauswahl
- Beachtung der Grundprinzipien von Visualierung (angemesser Plottyp, korrekte Darstellung der Daten, Klarheit, ...)
- Der Code wird nicht bewertet
