---
title: "PE 1.22 - Fortgeschrittene Datenanalyse, Statistik und Visualisierung"
---

Auf dieser Website findet ihr alle Informationen rund um das Bachelormodul PE 1.22 an der Deutschen Sporthochschule Köln.

In diesem Modul lernt ihr

* eigene Datenanalysen zu programmieren
* die statistischen Grundlagen hinter Machine Learning und Deep Learning
* Daten und Auswertungen ansprechend zu visualisieren
* Datenanalyse und KI auch aus ethischer Sicht kritisch zu beurteilen

Wir befassen uns in erster Linie mit Daten aus verschiedenen Bereichen des Sports (Leistungsdiagnostik, Ergebnisdaten, Sportökonomie, Gesundheit). Dabei habt ihr selbst die Möglichkeit eigene thematische Schwerpunkte zu setzen, indem ihr euch eigene Datensätze sucht oder eine Auswahl aus einem vorhandenen Pool von Datensätzen trefft.

Ihr braucht keinerlei Vorkenntnisse im Programmieren um an diesem Modul teilzunehmen. Alle notwendigen Grundlagen werden zu Beginn des Moduls vermittelt. Das Modul ist so aufgebaut, dass ihr Schritt für Schritt an die Themen herangeführt werdet.

Das nächstes Mal angeboten wird die PE 1.22 im **Sommersemester 2026**.

