---
title: "Lernmaterialien"
---

## Erweiterte Modellbildung & KI

### Präsentationen

-   **00 Intro:** [Slides](resources/00-intro.html)
-   **01 Lineares Modell:** [Slides](resources/01-linear-model.html)
-   **02 Lineares Modell — Advanced:** [Slides](resources/02-linear-model-advanced.html)
-   **03 Logistische Regression:** [Slides](resources/03-logistic-regression.html)
-   **04 Machine Learning:** [Slides](resources/04-machine-learning.html)
-   **05 KI:** [Slides](resources/05-ai.html)


### Übungen

Für die Übungen benötigt ihr das `pe122` package. Ihr könnt es mit dem folgenden Befehl installieren:

`remotes::install_github("pe1-22/pe122")`

::: {.callout-important collapse="true"}
### Probleme mit der Installation?
#### Mac: R möchte irgendeine große zusätzliche Software installieren?

Ihr benötigt die Command Line Tools von Xcode. Diese könnt ihr installieren, indem ihr im **Terminal** den folgenden Befehl ausführt: `xcode-select --install`. Danach R neu starten und die Installation des `pe122` packages erneut versuchen.

#### Mac/Windows: `API rate limit exceeded`
Github beschränkt manchmal den Zugriff auf Downloads von anonymen Nutzern. Ihr habt mehrere Möglichkeiten, dieses Problem zu umgehen:

- versucht es später nochmal.
- erstellt einen kostenlosen Github Account und verbindet diesen mit R, damit ihr als authentifizierter Nutzer keine Beschränkungen habt. Dazu befolgt ihr bitte diese Schritte:
1. Account auf Github erstellen: <https://github.com>
2. R-Package `usethis` installieren: `install.packages("usethis")`
3. In R folgenden Befehl ausführen: `usethis::create_github_token()`. Folgt den Anweisungen auf der GitHub Website.
4. Lasst den Befehl `gitcreds::gitcreds_set()` in R ausführen, um den Token zu speichern. Falls ihr den Fehler: `git not found` erhaltet, installiert zunächst git auf eurem Computer: <https://git-scm.com/install/>. Startet anschließend Positron neu und führt den Befehl `gitcreds::gitcreds_set()` erneut aus.
5. Jetzt sollte alles klappen. Versucht nochmal, das `pe122` package zu installieren: `remotes::install_github("pe1-22/pe122")`

- Ladet euch das Package als zip-Datei herunter von Github herunter (grüner Button "Code" > "Download ZIP"). Speichert die Datei in eurem aktuellen Arbeitsverzeichnis. Installiert es manuell mit `remotes::install_local("dateipfad/package.zip")`. Macht diese Schritte für die folgenden Packages (**in dieser Reihenfolge**): [gradethis](https://github.com/rstudio/gradethis), [ggcheck](https://github.com/rstudio/ggcheck), [sportsdata](https://github.com/smnnlt/sportsdata), [pe122](https://github.com/pe1-22/pe122).
- Benutzt die Online-Version (siehe weiter unten) 
:::

Im Anschluss könnt ihr die Übung starten, indem ihr folgenden Befehl in R ausführt (hier für Übung 1): `learnr::run_tutorial(name = "01-stat", package = "pe122")`

Alternativ ist es auch möglich, die Übungen ohne KI-Integration online zu bearbeiten:

-   **Übung 02**: [Online](https://smnnlt.shinyapps.io/02-stat/)
-   **Übung 03**: [Online](https://smnnlt.shinyapps.io/03-stat/)


#### Übungen mit KI-Integration

Es gibt alle Übungen auch mit KI-Integration. Dabei erhaltet ihr ein KI-generiertes Feedback, immer wenn ihr eine Coding-Aufgabe falsch beantwortet. Um die KI-Integration zu nutzen, müsst ihr folgende zusätzliche Schritte durchführen:

1. Ladet euch Ollama herunter: <https://ollama.com/download>
2. Öffnet Ollama. Erstellt einen kostenlosen Nutzeraccount und verknüpft ihn mit eurem Gerät.
3. Jetzt sollte alles klappen. Startet die Übung mit KI-Integration, indem ihr folgenden Befehl in R ausführt (hier für Übung 1): `learnr::run_tutorial(name = "01-stat-ai", package = "pe122")`

### Hackathlons

Die Materialien findet ihr auf Moodle.